import "./globals.css";
import { Roboto } from "next/font/google";

const inter = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "500", "700", "900"]
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// };

export default function RootLayout({ children }: { children: React.ReactNode }): any {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
